### ISSUE TITLE
interaction "with" steps

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#110]
Going trough the section "Terminology and Principles" in the visualization documentation, there arose the question if one can speak of an interaction "with" the steps as explained in the first section. We are not sure if this is regular terminology.

**Comment by mfranke93** [comment]
It is how we talk about it in InfoVis, and how we phrase it. The steps are, in general, some kind of computer program transforming the data (first from unstructured to structured, then to abstract geometrical primitives, then to concrete representations (like colored pixels)). Interacting *with* the steps means (implicitly or explicitly) modifying the parameters or configuration of the program that handles the step.

For example, switching from clustered to unclustered mode in our visualization means that you interact with the data transformation step primarily, because the spatial aggregation is removed. But as a consequence of a different visual representation (the smaller circles without the symbols), the visual mapping changes as well, so there is an interaction with that step as well.

**Comment by tutebatti** [comment]
Hm... I thought so already but have rephrased that anyway (such as "interaction regarding step xyz"), because it is pretty counter-intuitive for outsiders to the field. If my rephrasing distorts the meaning, you should, of course, correct that.

**Comment by mfranke93** [comment]
See my comment in the commit. I will have to rework that a bit anyways.
