### ISSUE TITLE
Blueprint for bug report

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#142]
I came up with the following blueprint to ask visitors that run into technical problems for further details:

> Thank you for telling us about this bug!
> 
> If possible, you can greatly help to find the exact cause of the problem by giving us some additional information. Any details answering the questions below can help. If you cannot answer a question or if it seems to complicated - do not worry.
> 
> 1) What operating system are you using (e.g. Windows 10, MacOS, Android...)?
> 
> 2a) What Browser are you using (e.g. Firefox, Safari...)?
> 
> 2b) Can you provide the exact version number of the browser (mostly accesible via the "help" menu of the browser clicking on "about" or the like)?
> 
> 2c) Have you installed any add-ons to your browser such as ad-blockers?
> 
> 2d) Can you provide a screenshot of the browsers developer console? (This is somewhat advanced. If your courious, you can just google "developer console" in combination with your browser.)
> 
> 3) If accesible to you despite the bug: can you send us the JSON file of the visualization state accesible via the Settings pane of the visualization under "Persist State"?
> 
> Thanks again for your help in improving Damast!

Any suggestions for improvement of the descriptions?

**Comment by mfranke93** [comment]
I was slightly irritated by the title at first, because "blueprint" has a special meaning with the Flask server :smile: 

 - If you are using such a checklist, maybe the bug description should be (1)
 - The screenshot of the issue itself (i.e., what it looks like in the browser, like in #141) should be a priority.
 - 2c) should be "ad-blockers or pop-up blockers"
 - 2d) should be (3), I think. Also, I think the console can be opened by pressing F12 in all browsers, so you could add that information.

Suggested structure:

1. Bug description
  a) textual description of the issue (what happens?)
  b) if possible: steps to reproduce (e.g., "click there, then click there")
  b) screenshot
2. User agent description
  a) OS
  b) Browser + version
  c) addons
3. additional information
  a) console screenshot
  b) state JSON

**Comment by tutebatti** [comment]
Thank you, that helps a lot!
