### ISSUE TITLE
Access to place URI page from map

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#146]
Another comment by the same visitor giving feedback reported in #144:

> It would be great to access the place URI page directly from the map.

Right now, the "mechanics" are either hovering displaying a tooltip. One can probably not use that as a link to the place URI page as it vanishes when moving the mouse. Clicking on the place (or the glyph) brushs and links, which then allows to go to the place URI page from the location list. So there is probably no easy solution. Maybe one could open the same popup as with the hovering with a right-click and make the tool tip persistent? Just an idea.

**Comment by tutebatti** [comment]
> Maybe one could open the same popup as with the hovering with a right-click and make the tool tip persistent?

Another reason to have the tooltip persistent is to be able to copy the content. This was also "requested" by the same visitor.

**Comment by mfranke93** [comment]
> Another comment by the same visitor giving feedback reported in #144<https://github.com/UniStuttgart-VISUS/damast/issues/144>:

> > It would be great to access the place URI page directly from the map.

> Right now, the "mechanics" are either hovering displaying a tooltip. One can probably not use that as a link to the place URI page as it vanishes when moving the mouse. Clicking on the place (or the glyph) brushs and links, which then allows to go to the place URI page from the location list. So there is probably no easy solution. Maybe one could open the same popup as with the hovering with a right-click and make the tool tip persistent? Just an idea.

I understand the intent. One issue I see, however, is that map glyphs are not always just one place. The indirection via the location list solves that.

Making the popups "stay" could help here, but introduces additional complexities and modalities both to the user interface (which would need to be explained and learned) and to the code. Also, in my experience replacing the default behavior of the right click is not a good idea. But I will think about this some more.

> [I can still not use any of the github features at the side of the mask (assignees, labels...). I assume I have no rights to do so. Is this intended?]

Yes. See my email from Friday afternoon.

**Comment by mfranke93** [comment]
One idea could be to make the popup in the map different to those in the other views. Of course, there would then be some inconsistencies here, which I do not like. Plus, there is some implementation effort. The big question would be whether it would be desirable to be able to "pin" the tooltips in the other views as well.

Especially for the map, it would be an option to have a "pinnable" tooltip, such as shown in the example on the Leaflet website: https://leafletjs.com/index.html

**Comment by tutebatti** [comment]
> a "pinnable" tooltip

If I understand correctly, it is not pinnable in the sense that one has an option to pin it or not but the tooltip stays open and can be closed by clicking on the x. Right? In theory, this would be ideal, especially if one can navigate from there to the place URI page. On the other hand, I would rather take the "detour" via the location list. Less effort needed, except for a video as suggested in #149.

**Comment by mfranke93** [comment]
> If I understand correctly, it is not pinnable in the sense that one has an option to pin it or not but the tooltip stays open and can be closed by clicking on the x. Right? In theory, this would be ideal, especially if one can navigate from there to the place URI page. On the other hand, I would rather take the "detour" via the location list. Less effort needed, except for a video as suggested in #149<https://github.com/UniStuttgart-VISUS/damast/issues/149>.

Well, pinning it would mean that it temporarily stops following the mouse, or disappearing. Then, some action (like clicking an x) could close it. Of course, that introduces additional state into the UI, which both makes it more complex to use and explain, and needs to be programmed and tested to check for edge cases.

I personally think the user interface should not become even more complex, especially since other feedback you submitted today indicates it already overwhelms new users. I'm not surprised by that: it is a powerful, and hence complex, interface and is geared towards experts who took the time to learn it. On the other hand, I understand how this could be useful. Maybe we can come up with a good compromise. If #147 makes the place URI page show more of the information currently only in the tooltips, being able to copy them would not be necessary as long as there was a quick way to navigate to the place URI page. Such as a very simple second tooltip that appears and stays, and only contains the link(s) to the URI page(s).

**Comment by tutebatti** [comment]
> If #147 makes the place URI page show more of the information currently only in the tooltips, being able to copy them would not be necessary as long as there was a quick way to navigate to the place URI page. Such as a very simple second tooltip that appears and stays, and only contains the link(s) to the URI page(s).

I was thinking a very similar thing. I think that even accessing the place URI page from the location list might be a good solution, especially if a glyph represents more than one place. What do you think, @rpbarczok?

**Comment by mfranke93** [comment]
I implemented something experimental on a branch. It is a bit awkward, but might be a nice solution for "power users:" Holding the shift key and then clicking on a glyph does something different than just clicking. If the glyph represents just one place, that place's URI page instantly opens in a new tab. If there are more than one places contained, a popup window opens (similar to the info boxes) which lists the places and provides links to the respective URI pages (see screenshot). Since this is a "normal" dialog window, it can be clicked on, and disappears when closing it (X) or clicking on the backdrop.

![image](https://user-images.githubusercontent.com/9373678/168636087-f6dd8bc6-836e-41af-a517-68e17501bf09.png)

Let me know if this would work for you. If you want, I can also deploy this to the test server so you can try it out. As I said, with the shift-click and the extra dialog it is a bit awkward, but some users might want to use it.

**Comment by tutebatti** [comment]
Just tried it and really dig it. Together with a solution for #147 and the videos, this should be great.

**Comment by mfranke93** [comment]
![image](https://user-images.githubusercontent.com/9373678/168783026-341d4503-e0b1-48f9-b2ee-eb63137bb70b.png)

@tutebatti I added the respective info text content under "Interaction" after "Selection". Please let me know if it is okay, then I can merge it.

**Comment by tutebatti** [comment]
Can this be closed now?

**Comment by mfranke93** [comment]
https://www2.visus.uni-stuttgart.de/damast/testing/place/14/evidence

:)
