### ISSUE TITLE
Listing pieces of evidences in place URI pages?

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#147]
Connected to #144 and #146, a reason to generate reports is that it is the only way to have access to the detailed pieces of evidences. The visitor seemingly wanted to create reports to read about the different pieces of evidence of a specific place. What would you say, @rpbarczok?

**Comment by mfranke93** [comment]
Reusing the code from the reports to list the evidences in the same way as in the report would be a possibility. There are some things you should discuss and decide on, though:

 - Where would the list of evidences be in the place URI page? Currently, the sections are: Names in other languages, external links (URIs), religions, persons, sources, how to cite.
 - The place URI page is at the moment a (relatively) short page with an overview of data. Listing the evidences explicitly will dramatically increase the length. Keep in mind that in the reports, there are usually many filters active. Here, only one filter (the place must match) would be active. For example, for Halab in the testing database, I currently get 141 evidences. Are you okay with inflating the page sizes that much? This also affects where the evidence list would be placed (point 1), because it would need to be scrolled past to get to the rest.
 - Related to point 2, the place URI pages for places with many evidences will also need considerably longer to load, as a lot more data has to be collected, calculated, and rendered.

**Comment by tutebatti** [comment]
Thanks. These are the right questions.

Regarding your third bullet point: I didn't know they were automatically generated. With a growing database, this makes a lot of sense, of course. But I assume there's no easy way to have a similar mechanism regarding generation, deletion, and changes for the place URI pages compared to the reports.

**Comment by tutebatti** [comment]
> And in light of that my previous reply sounds very harsh and condescending, so apologies!

No worries!

> I think that would be a better place for it, especially concerning the placement and scrolling issue I detailed above. My suggestion would be a link directly under the "Religions" heading: "Show detailed list of historical evidence". This would direct to a separate page (e.g., `/place/XYZ/evidence`) with just the place name and the evidence list, which would look the same as in the report. Of course, the page would also have a link back to the overview page.

That sounds like a good solution to me. I will talk with @rpbarczok soon and we'll let you know what we decided.

**Comment by tutebatti** [comment]
I talked to Dorothea and Bernd. We can do it as suggested: have the evidences on a separate page.

**Comment by mfranke93** [comment]
https://www2.visus.uni-stuttgart.de/damast/testing/place/14/evidence

:smile:

**Comment by tutebatti** [comment]
I also just checked it. Great work, thanks! Could we add a table of contents? And is it possible to move the short section "Religions" that has a somewhat overview character to the top? (Or maybe there are reasons not to do that?)

Just another remark: On the testing server, before logging in, I have the same problem as #139 while the Add-on "Ghostery" is active.

**Comment by mfranke93** [comment]
> Could we add a table of contents?

Sure. The reason I did not do it from the start is that the main focus should be on the evidences themselves, so I thought it better if they were the first thing. Keep in mind that most of these pages are considerably shorter than the Halab one. But yeah, a TOC is a good idea.

> And is it possible to move the short section "Religions" that has a somewhat overview character to the top? (Or maybe there are reasons not to do that?)

Again, the focus on the evidences themselves. The rest is just for reference.

Honestly, this page is 1:1 the HTML version of the report, for one filter (place ID equals the one of the place), and without some of the sections (places, because it doesn't make sense; query description; how to cite (mentioned in parent page)). As such, I kept the order of sections the same as in the reports. Although it ultimately does not matter. If you would like to have the religions first, that is not a huge change to make.

> Just another remark: On the testing server, before logging in, I have the same problem as https://github.com/UniStuttgart-VISUS/damast/issues/139 while the Add-on "Ghostery" is active.

Interesting. I was sure I fixed that. I'll look into it, thanks for the heads up!

**Comment by mfranke93** [comment]
I have now added the TOC and done some minor styling fixes. The current version is on the testing server. Let me know if you still want the religion section first, otherwise I would see this issue as completed.

**Comment by tutebatti** [comment]
Thank you! In fact, I would put the religion section first: it gives a nice overview. Users not completely familiar with our data structure might be thrown off by repetitions of the same group, e.g. the first two here: https://www2.visus.uni-stuttgart.de/damast/testing/place/114/evidence#religions
