### ISSUE TITLE
Access to existing reports for visitors

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#155]
In our public version, there are no users with log-in, only visitors. Access to existing reports is thus limited to either saving the URL or saving the visualization state file and creating the report anew. There are several smaller changes which could improve access to existing reports for visitors:

1) Change the label of the report functionality in the _Docs_ menu to "Create or access report from database".

2) Add a section to that page under .../reporting/ with (a) a short explanation that .../reporting/#UUID# will lead to the report directly and possibly (b) a field to enter the UUID and a button redirecting the visitor to the report.

These are only suggestions, of course. The general point, i.e. less easy access to existing reports for visitors without log-in, is clear, isn't it?

**Comment by mfranke93** [comment]
We discussed whether visitors should see the list of reports in a meeting once, and decided against it, because there would just be too many anyways. We also discussed the general access to reports [here](https://github.tik.uni-stuttgart.de/frankemx/damast/issues/167), and settled on the choice that is pragmatic and minimizes storage of GDPR-critical data ("Datensparsamkeit"): If someone knows the UUID to a report, they can access it.

Our decision then was, thus, not to offer visitors a list of reports they themselves provisioned (which could be possible using cookies). Obviously, that would be the most convenient possibility, but, as discussed, not the most ideal one GDPR-wise. Plus, it only works if the visitor uses the same computer and browser each time.

With your suggestion, I don't see a large improvement: Is it more convenient to copy the UUID, save it somewhere, and then paste it into a text field; than to bookmark the report in the browser (or copy the entire URL instead)? Concerning other visitors' reports, the entire URL to the report is in the "How to cite" section anyways. Further, at the time the explanation in 2a) is visible, it is already too late if the visitor did not save the UUID when they first opened the report.

**Comment by tutebatti** [comment]
> We discussed whether visitors should see the list of reports in a meeting once, and decided against it, because there would just be too many anyways. We also discussed the general access to reports [here](https://github.tik.uni-stuttgart.de/frankemx/damast/issues/167), and settled on the choice that is pragmatic and minimizes storage of GDPR-critical data ("Datensparsamkeit"): If someone knows the UUID to a report, they can access it.
> 
> Our decision then was, thus, not to offer visitors a list of reports they themselves provisioned (which could be possible using cookies). Obviously, that would be the most convenient possibility, but, as discussed, not the most ideal one GDPR-wise. Plus, it only works if the visitor uses the same computer and browser each time.

This all still holds true. I did not want to discuss this again, to be sure.

> Is it more convenient to copy the UUID, save it somewhere, and then paste it into a text field; than to bookmark the report in the browser (or copy the entire URL instead)?

I thought less about convenience than about absent-minded academics noting down the UUID (not saving the URL) and then not knowing what to do. Plus: There's no access to the reports via clicking through the different pages for now, except for some explanations in the documentation. There, we actually refer back to the startpage. (With a link to the startpage in general.) On the startpage it then reads:

>  Note that the UUID or permanent link needs to be recorded by the user to access the report later!

However, we do not provide information about the exact structure of the URL, namely .../reporting/#UUID#. So we could change that on the startpage, too.

Generally, I think of visitors who easily give up when things are not easy. ;)

**Comment by mfranke93** [comment]
I see. I am still skeptical this situation will happen (I think if someone is too absent-minded to note down a URL, they won't note down the UUID either), but it cannot hurt. And yes, reading and parsing URLs is something I don't think about much, but right now it is not obvious, especially outside of the actual report page (I would say if I was in a report, the title said "Report X", and the URL said .../reporting/X, the coin would drop).

I'll come up with a suggestion.

**Comment by mfranke93** [comment]
Done. @tutebatti please leave a review for #156. Once you have it approved, I'll merge it into the next release.
