### ISSUE TITLE
Clustered and unclustered in info text for Settings pane

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#22]
While rephrasing the info text for the Settings pane, I would like to explain how the clustering generally works. I write "generally" because there needn't be an exact description of the mechanism. So, when zooming out (or moving the center point of the map), how are the symbols aggregated or clustered - is there anything weighing one place as against another? Is it just the average of the places clustered together? I understand that it's probably not that easy to explain.

**Comment by mfranke93** [comment]
The clustering algorithm currently in use is nothing spectacular. In fact, I have wanted to do something better here for a long time, but the specific set of requirements that clustering stuff on maps has (in my opinion) is a very hard problem to solve, and I have not found a solution I am content with yet.

In simple terms, what the current clustering algorithm does is the following:

 1. The symbol is placed in the middle of all the cities it represents (the centroid of those points) *without* any prioritization or weighing (i.e., the average of the places, as you put it).
 2. The cluster symbols have a specific *radius.* The algorithm ensures that two cluster centroids are never closer together that twice that radius. This means that the symbols of two clusters will never overlap.
 3. Clusters are recalculated if either the data change (new filters, ...), or the zoom level changes. Moving/panning the map around without zooming will not trigger re-clustering (and the result would be the same in any case).

**Comment by tutebatti** [comment]
Do I understand correctly that 2. is used for the placement described in 1.?

**Comment by mfranke93** [comment]
The symbol is *always* placed in the centroid of the contained places/cities (1). The algorithm (2) ensures that the centroids are never too close to each other by deciding which cluster each place should be put in.

> Do I understand correctly that 2. is used for the placement described in 1.?

In short: no, because cause and effect are mixed up. The placement depends *only* on which places are contained in the cluster, and not on other clusters. But a side effect of how the places are assigned to the clusters is that the centroids are always at least that distance apart.
