### ISSUE TITLE
Menu bar differs between visualization and other pages

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#24]
The menu bar in the visualization includes more options than on the other pages; e.g., the impressum is not shown in the menu of the start page.

**Comment by mfranke93** [comment]
The visualization page layout tries to save space for the interesting part. It has no footer, which is why the Impressum and GDPR links are moved to the header. On all other pages, these links are located in the footer instead.

Side note: The `invalid` label is usually used to mark issues that are invalid, not issues that describe invalid behavior (that would be a `bug`). I'm not sure that was the intention here.
