### ISSUE TITLE
"Hovered component" in info text of Timeline view

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#36]
In the current info text of the timeline view, one can read:

> In <em>only active</em> mode, filtered-out data is hidden from the visualization, and <em>linking</em> only shows the timeline of the currently hovered component.

I am not sure how to understand "hovered component" here.

**Comment by mfranke93** [comment]
That is historical. In earlier versions, brushing and linking happened as soon as you hovered over something with the mouse. So, for example, if you would place the mouse over a glyph in the map, the timeline would have shown only the data from the cities represented by the glyph.

The brushing and linking still works, but now you have to **click** instead of just hovering. The concept of brushing and linking ([Buja et al., 1991](https://dl.acm.org/doi/abs/10.5555/949607.949633)) should be explained somewhere in any case. It is an important technique for exploration in interactive visualization. Maybe we could reformulate this as *"... of the currently brushed selection"* (although that might be interpreted incorrectly by some, because selecting a rectangular area in a timeline is sometimes also called "brushing" or "brush selection") or *"... of the currently brushed component."*

"Component" just means that it can be anything in any view that represents one or more data items (evidences). For example, a map glyph, a place name in the location list, a source in the source view, ...

**Comment by tutebatti** [comment]
What is the difference between "brushing" and "selecting"? From what I read in the info texts until now, this is similar?

**Comment by tutebatti** [comment]
Nevermind the question, I checked this: https://en.wikipedia.org/wiki/Brushing_and_linking

So "selecting" is what the user does, "brushing and linking" is what follows in the visualization, right?

**Comment by mfranke93** [comment]
Yes. Selecting triggers brushing.
