### ISSUE TITLE
Term "node" in info text of Religion hierarchy

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#44]
I suppose the term "node" in the info text of _Religion hierarchy_ is used because the whole hierarchy is represented as an indented tree. For the average user, the term "bar" might be clearer. Would it be technically wrong?

**Comment by mfranke93** [comment]
I would really like to avoid "dumbing down" the texts to the point where proper visualization terms are not used at all, just because visitors might not know them. Rather, these terms should be introduced properly. Of course, it needs to be understandable, and I appreciate your effort. For this specific case, I would suggest the following:

In the first paragraph, extend

> The hierarchy is represented by an indented tree visualization.

to

> The hierarchy is represented by an indented tree visualization. Hierarchy nodes are represented by rectangular bars, with a short label for the religion to their left.

Then, it would be fine to use "bar" in the rest of the text.

In total, it might be a good idea to have a complete, connected explanation of the visualization (my suggestion in #33). There, important visualization terms (multiple coordinated views, linking and brushing, selection, the visualization types used) and maybe also computer-technical terms like zooming, panning, and hovering could be introduced in an understandable way.

**Comment by tutebatti** [comment]
Thank you. I already have something similar in my local version and will adapt this to your suggestion.

Regarding your general remark, I absolutely agree that proper visualization terms should be introduced and explained. After all, rephrasing the info texts etc. is meant - according to #8 - not only for the publication of DhiMu data and, even in this case, the entire project contributed to both disciplines, humanities and visualization science.

Second, for me, too, the need for a complete, connected explanations becomes more apparent. So, if we agree to do this, does this affect our workflow concerning the rephrasing of info texts as against you writing a documentation? I am open to any suggestions.

**Comment by tutebatti** [comment]
Also, is there a technical difference between an abbreviation and a short name?

**Comment by mfranke93** [comment]
> Second, for me, too, the need for a complete, connected explanations becomes more apparent. So, if we agree to do this, does this affect our workflow concerning the rephrasing of info texts as against you writing a documentation? I am open to any suggestions.

I would say no, at least not at the start. My idea is to let the server "paste" all texts together into a longer page and add some more text at the top (like the introduction of terms). I think I can just start implementing that on the same branch, and then we can see as we go how well it works.

One thing we might want to do is increment the level of headings by one in the info texts (`<h3>` as the top level) so that in the long text, we can have `<h2>` elements for the individual info text headings. But that is a very quick change. 

> Also, is there a technical difference between an abbreviation and a short name?

Probably. But in the case of the religions, "abbreviation" is the better word anyways, I think.

**Comment by tutebatti** [comment]
> I think I can just start implementing that on the same branch, and then we can see as we go how well it works.

Will you file the respective issue or should I do that?

**Comment by mfranke93** [comment]
Already done :) #46
