### ISSUE TITLE
Terminology for "Religions"

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#45]
It is very well possible that you have discussed this (extensively) earlier. If so, please point to the respective discussions in case they are documented.

At any rate, I run into problems with the terminology while rephrasing the info texts and, partially, writing the summary for the start page. 

(1) In the current info texts, the term _religion_ as well as _religious denomination_ is used. The historians in their planned publication argue to use the generic term _religious group_. From my humanities point of view, the latter is preferable. However, it can pose problems when talking about "grouping" or "groups" of phenomena when describing the visualization. 

(2) From the computational side, I think the term _religion_ is used in the back-end etc., only discerning between first, second, and third level (e.g., Islam, Shia, 5s). Correct me, if I'm wrong. Is there any reason why the average user needs to be confronted with this terminology besides the fact that the religions are presented and handled according to a hierarchy? In other words, for the user, one could speak of _"main" religion_ and _religious group_ instead of _religion on 1st/2nd level_. I am still looking for something better than _"main" religion_.

(3) I strongly discourage the use of "Abrahamic" religions, as it is a term not entirely free from ideology. (I am not saying it is a problematic ideology, but it is an ideology nonetheless.) Instead, I suggest to just list the three religions Christianity, Islam, and Judaism.

Any thoughts and ideas from your side are welcome. Thanks!

**Comment by mfranke93** [comment]
I think @rpbarczok can say more, but my 2 cents:

1. We used "religious denomination(s)" in our collective publication (VIS4DH 2019). I vaguely remember that we discussed terminology extensively then, but it was quite a while ago (mid 2019). I seem to remember that, since in the project then (DhiMu), the focus was on *institutionalized* religion, we avoided "groups" because that does not necessarily mean institutionalized. But you are the experts here, so the final decision on terminology should be yours.
2. The terms used in code are not relevant at all for visitors. It is just more pragmatic to call that table `religion` than `religious_group` or something along those lines. As to the hierarchy levels: since I authored the initial versions of the info texts, the descriptions are of course a bit technical. But here, I also wanted to keep it generic enough: From the way the hierarchy is built from the database, it *really* does not care whether the top-level nodes of the tree are "main" religions or not. This is just a decision made in the data, not the visualization. But again, I defer to your expertise.
3. That's good to know.

**Comment by tutebatti** [comment]
> From the way the hierarchy is built from the database, it _really_ does not care whether the top-level nodes of the tree are "main" religions or not.

Exactly, and the "grouping" of other religions to "OTH" really proves that.

What is more, again, "grouping" as in the previous sentence terminologically interferes with "religious groups". Other terms such as category, class, etc. can all be problematized by humanists. (They love that. :wink:)

**Comment by rpbarczok** [comment]
1. I think we should use the term in line to the Damast text. There, we explain why we use the term _religious group_ and which groups we describe by that.
2. That is always the problem that we have when dealing with hierarchical structure. In the case of Islam, Judaism and Christianity, we need these terms when there is no specification about which subgroup a specific source speaks. So, main religion is perhaps the wrong term. So "general" religious affiliation or something like that is meant.

**Comment by rpbarczok** [comment]
3. We can choose not the use the term abrahamitic. I usually do not use the term, because in my view it is not a historical term, but a theological one - and I think one of recent times, not something people in the medieval times would refer to.

**Comment by tutebatti** [comment]
Thank you, @rpbarczok. "General religious affiliation" seems to work well, as, e.g., in the following:

> The general religious affiliation (e.g., Christianity) is on the first level of the hierarchy. For other religions beside Christianity, Islam and Judaism, we made the pragmatic choice to group them under the category <em>Other</em> [...]

> The religious groups each have a distinct colour.
  For Christianity (red), Islam (green), and Judaism (blue), the religious groups belonging to that general religious affiliation do have hues of the same colour.

Note that I avoided "Abrahamic" as against the original info text.

Feedback on how @rpbarczok 's suggestion works in that example (and possibly others) is welcome.

**Comment by tutebatti** [comment]
I will leave it at that.
