### ISSUE TITLE
Clarification on filtering in "Advanced mode"

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#48]
In the current info text of the _Religion hierarchy view_, the following example is given to explain _Advanced mode_:

> For instance, analysis may require to show places where the Syriac Orthodox Church (SYR), the Armenian Church (ARM), and the Church of the East (COE) coexist, but not those where only one of the three is present.

The procedure then described to control the filters mentions three columns, each with two religious group out of the three.

What about a column with all three of them?

In my understanding, there is a difference between:

- checking COE, ARM, and SYR in _Simple mode_
- in _Advanced mode_, using one column with COE, ARM, and SYR checked
- dito, using three columns with one out of the three checked in each column as described above
- dito, using four columns, three as mentioned, the fourth checked with all three religious groups

Correct? If so, I would mention this as briefly as possible in the info text.

**Comment by mfranke93** [comment]
Okay, so there is a lot of different variants here. I have made a screenshot for each to make sure we are on the same page:

**Variant 1a:**
> The procedure then described to control the filters mentions three columns, each with two religious group out of the three.
![image](https://user-images.githubusercontent.com/9373678/149506101-5e4f8d9d-7c1d-4eab-aa1a-a9f3eacd49d3.png)

**Variant 1b:**
> What about a column with all three of them?
![image](https://user-images.githubusercontent.com/9373678/149506146-f7285a06-34cd-4f2d-948a-e2eed5cb75da.png)

**Variant 2a:**
> checking COE, ARM, and SYR in Simple mode
![image](https://user-images.githubusercontent.com/9373678/149505840-586b1a7c-0d50-4d35-a04e-134b4dbe3725.png)

**Variant 2b:**
> in *Advanced mode,* using one column with COE, ARM, and SYR checked
![image](https://user-images.githubusercontent.com/9373678/149505894-c0567b1d-13c7-485a-b9fe-891b8ce5fc69.png)

**Variant 2c:**
> dito *[What does that mean here? This would be my best guess.]*, using three columns with one out of the three checked in each column as described above
![image](https://user-images.githubusercontent.com/9373678/149505932-1ca6b49b-23c2-4f46-80d4-3147f3335d6f.png)

**Variant 2d:**
> dito, using four columns, three as mentioned *[I suppose 2c?]*, the fourth checked with all three religious groups
![image](https://user-images.githubusercontent.com/9373678/149506263-62e7fba4-a738-4f65-b1fc-bbe7f0002c72.png)

---

The principal thing to understand is how the simple and advanced mode work. From that, these questions can then be answered using Boolean logic and/or set operations:

 - In *Simple mode,* a logical **OR** is used between all checked religions. This means: an evidence matches if *any* of the checked religions are connected to it. At the same time, a place is then shown if *any* of the religions appear with that place in an evidence.
 - In *Advanced mode,* each column uses logical **AND,** now associated with places (since one evidence only ever has one religion): Religion X is in place P *and* religion Y is in place P *and* religion Z is in place P (if X, Y, and Z are checked in that column). *Between* columns, logical **OR** is used, so a place matches if it fits *any* of the columns. Consequently, if the place matches and the religion is one of the ones checked, the evidence matches.

## For variant 1a and 1b, this means:

 - 1a = (COE **AND** ARM) **OR** (COE **AND** SYR) **OR** (ARM **AND** SYR)
 - 1b = (COE **AND** ARM) **OR** (COE **AND** SYR) **OR** (ARM **AND** SYR) **OR** (ARM **AND** SYR **AND** COE)

However, these two statements are equivalent. If a city has **all three,** it already matches *each* of the first three statements. And since there is a logical **OR** between them, matching *just one* suffices. So no, it is not necessary to have the fourth column in 1b, it does not do anything (except maybe make the filtering slightly slower).

## For variants 2a–d, this means:

- Variant 2a and 2c are **equivalent:**
   - 2a = COE **OR** ARM **OR** SYR
   - 2b = (COE) **OR** (ARM) **OR** SYR 
- Variant 2b and 2d are **equivalent,** because the **OR** between the columns means only one column needs to match. And if a place has all three religions (variant 2d, column four), that already matches for each of the previous three columns. So the fourth column again is a (logical) no-op.

**Comment by tutebatti** [comment]
To clarify (sorry!), "dito" meant "in _Advanced mode_.

**Comment by mfranke93** [comment]
That is how I interpreted in the end, so my answer remains unchanged :+1:

**Comment by mfranke93** [comment]
Come to think of it: Variants 2a, c, d are *all* equivalent in the end, and 2c does something different. I will edit my response above.

**Comment by tutebatti** [comment]
Thank you for this extensive clarification. I already had assumed something had slipped "my" logic. If I'm somewhat representative of a user not dealing with Boolean logic on a daily basis, we are well advised to clarify this behaviour. Your answer will serve well for that.

However, note that

> For instance, analysis may require to show places where the Syriac Orthodox Church (SYR), the Armenian Church (ARM), and the Church of the East (COE) coexist, but not those where only one of the three is present.

is ambiguous, because 1a/1b OR 2b could be meant. So, an addition such as "all of the three" or "two out of the three" in that sentence would be necessary.

**Comment by tutebatti** [comment]
> Come to think of it: Variants 2a, c, d are _all_ equivalent in the end, and 2c does something different. I will edit my response above.

So Boolean logic is tricky for anyone :wink:  (cf. Kahneman's _Thinking, Fast and Slow_).

**Comment by mfranke93** [comment]
Agreed. Right now it sounds like all three need to coexist.

And regarding Boolean logic, that is an important point. Especially since there a critical difference between *inclusive* and *exclusive or* that is sometimes hard to make out in language. In Boolean logic and programming, "or" usually refers to an *inclusive* or (X or Y, or both), but when used in language, depending on context, it could be exclusive (either X or Y, but not both). Think of "Do you want red wine or white wine with your dinner?", which is a logical place for an exclusive or. But when we say "Show places with COE or ARM" (simple mode), we probably mean it inclusively, and not as "don't show places where both are present".

**Comment by tutebatti** [comment]
Good point. Probably the "equations" (1a = (COE **AND** ARM)...) provided in your extensive answer can be included in the description in some form.
