### ISSUE TITLE
Brushing of clustered map glyphs

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#49]
When selecting a place from the location list, data is brushed and linked. However, the respective map glyph representing that location may represent first level religions through a _highlighted_ circle, even though the selected place does not have any evidences belonging to that first level religion. Is this behaviour intended?

This screenshot shows the selection of Abu Tij, who only has COPT evidences. From the _Religion view_, this is obvious, not so from the glyph.

![grafik](https://user-images.githubusercontent.com/7239968/149511603-ec877bb6-9344-48b8-9d32-c7bbcc463db2.png)

**Comment by mfranke93** [comment]
What I think is happening here: The glyph represents *not only* Abu Tij, but also some other place, which has Islamic evidence. Please check whether that is the case, otherwise this could be a bug. The glyphs are always highlighted in full, never partially. I suppose partial highlight might be possible, but:

1. It would be some implementation effort.
2. Would that stop at the circle level (the circles are not always the main religions, it depends on what is visible), or would it go deeper into circle segments? If so, at some point these could be hard to see.

**Comment by tutebatti** [comment]
Exactly, the map glyph here (and in similar cases) aggregates multiple places, among which some might have Islamic evidence.

Regarding 2., I asked myself the same question. How far would that go?

I think it suffices to state the current behaviour in the info text / documentation. A quick glance of the user at the _Religion view_ solves the "issue" immediately.
