### ISSUE TITLE
Partial Highlighting in Religion view

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#53]
I do not understand the following sentence in the current info text of the _Religion_ view.

> In only active mode, a node is entirely colorful if any data with that religious denomination is not filtered out, and less colorful otherwise.

**Comment by tutebatti** [comment]
I rephrased like this:

> in <em>Only active</em> mode, the colour of a node is saturated if <em>any</em> data with this religious group is not filtered out.
  If the religious group has been filtered out, its node is displayed in a less saturated colour.

**Comment by mfranke93** [comment]
The new phrasing is incorrect, but I agree the old one is unclear. What is meant is that, in *only active* mode, since the inactive part is not displayed, the entire bar is one rectangle, which is fully saturated. In *all data* mode, a **part** of the bar is displayed less saturated: the proportion of evidences that do not match the filters. But not the **entire** node is less saturated:

**All data:**
![image](https://user-images.githubusercontent.com/9373678/149945260-a95eaf7b-2b98-4140-a628-b6c1a3edcef3.png)

Same filters, but **only active:**
![image](https://user-images.githubusercontent.com/9373678/149945325-fcc6e8dc-3fa4-4dba-945a-c97fa52dce50.png)

**Comment by mfranke93** [comment]
Note, though, that in confidence mode the bar can consist of more than one segment even in *only active* mode:
![image](https://user-images.githubusercontent.com/9373678/149945464-51cb6202-7d6e-410e-b84b-f5a78f6d4bbf.png)

However, all segments are saturated, whereas there are desaturated (inactive) ones in *all data* mode:
![image](https://user-images.githubusercontent.com/9373678/149945557-53afbf17-277a-4351-b6d8-da5c1c78ee72.png)

**Comment by tutebatti** [comment]
Thank you for clarification. Thinking about it, it is complicated because there are four different options:

- only active, religion mode
- all data, religion mode
- only active, confidence mode
- all data, confidence mode

All of them behave a little differently, even though the principles are the same in respect to the two different modes (_Show filtered data_; _Display mode_). I will have to think about rephrasing this the right way, without repetition or becoming overtly complicated. Maybe even use a list as in this post?

Btw: the preview of the implemented buttons looks promising. :wink:

**Comment by mfranke93** [comment]
Ironically, at least in my opinion, it is way easier to reason about from the implementation side. In the end, the different modes do exactly the same thing in each view:

 - In *only active* mode, some parts are hidden/filtered out.
 - In *confidence mode,* data is aggregated by confidence level instead of by religion.

I think the second point is what makes it behave so "differently" in this view, because each bar represents exactly one religion, so in *religion mode,* each bar has only one (or two) segments, but can have more in *confidence mode.* In other views, in some cases the religion aspect disappears completely in *confidence mode,* and the "difference" is not as stark. 

> Btw: the preview of the implemented buttons looks promising. :wink:

Thanks! They are ready to ship for `v1.0.4`, so you will have them soon!

**Comment by tutebatti** [comment]
> I think the second point is what makes it behave so "differently" in this view

Exactly!
