### ISSUE TITLE
Default aspect of Confidence

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#65]
_Religion confidence_ is the default aspect visualized when in _Confidence_ mode. What is the reason for this? Should we explain the reason?

**Comment by mfranke93** [comment]
I cannot find where we discussed this, so I assume it was in one of our meetings (a long time ago, before you (@tutebatti) were involved). It might also be a case of:

> I (@mfranke93) am just going to set it like this for now, because we need to start somewhere. I then ask everyone else if that is okay, and never get any negative feedback or different suggestions, so it stays with my initial choice.

That kind of thing has happened in a few places, and in most cases, I either get asked to change my initial, default behavior (like: show the qualitative timeline by default), or it stays as it is because no-one objects (like: the default layout of views). 

 Maybe @rpbarczok has a good rationale. Otherwise I don't see any reason to explain the reason. *Something* has to be the default.

**Comment by tutebatti** [comment]
> _Something_ has to be the default.

True, but I think @rpbarczok et al. will explain in the Prolegomena that mostly, a low level of certainty regarding _Religion confidence_ can be avoided by using the group which is higher in the hierarchy instead. Right?

**Comment by rpbarczok** [comment]
Well it's true. It is one of the cases of Max just setting a default and never got any negative feedback. It is hard to foresee what the most common interest of future user will be, so there is no rationale here so far. Since you have to switch on the confidence view on purpose  anyways, I think a user will have already an idea of what you want to achieve. At least that's how I used it. Therefore I never thought thoroughly about it. Additionally, using the confidence view makes only sense (in my opinion) when you switch on all confidences, so you have to go astray from the defaul anyway.

**Comment by tutebatti** [comment]
> Additionally, using the confidence view makes only sense (in my opinion) when you switch on all confidences, so you have to go astray from the default anyway.

I think there's a misunderstanding. What is meant with "default" here is where the eye symbol is set in the _Confidence view_, not what checkboxes in that view are checked.

Other than that, I would then go with what you stated: if there's really no obvious rationale, something has to be the default and there's nothing to explain.
