### ISSUE TITLE
Terminology: selecting/brushing+linking vs. filtering/setting active

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#72]
To have a consistent terminology across all info texts, I would distinguish between

- "selecting", which is connected with "brushing+linking" - here, only one element can be selected at once
- filtering, which sets data active or inactive: in _All data_ mode, inactive data is represented by less saturated colors; in _Only active_ mode, only active data is visible

Probably one could add more general principles which are the same in all views or can be attributed to the two things listed above.

At any rate, it would be important to explain these two basic principles on the start page (briefly) and in the documentation (in more detail) and use the terminology introduced there consistently throughout the rest of the descriptive texts.

**Comment by tutebatti** [comment]
I just saw that there is already a section "terminology and principles" in the new (?) documentation. :)

**Comment by mfranke93** [comment]
Yes, as I already mentioned [here](https://github.com/UniStuttgart-VISUS/damast/issues/6#issuecomment-1015633401) ;)

**Comment by tutebatti** [comment]
I'm sometimes overwhelmed with the mass of information. (Am I alone with this?) :smile: 

Do you think it is better if you start (not now, but principally) writing that section instead of me writing things not correct that have to be reworked a lot?

**Comment by mfranke93** [comment]
> To have a consistent terminology across all info texts, I would distinguish between
> - "selecting", which is connected with "brushing+linking" - here, only one element can be selected at once
> - filtering, which sets data active or inactive: in All data mode, inactive data is represented by less saturated colors; in Only active mode, only active data is visible

I think/hope that this is already pretty consistent, but better make sure. And yes, that would be the way to distinguish those.

> I'm sometimes overwhelmed with the mass of information. (Am I alone with this?) :smile:

Not at all! But that is one thing why I try to keep issues to a smaller granularity and branches short-living. The issue where I mentioned that has been active for very long, and the branch as well. We have also touched on many different topics in that issue, so no wonder ;) we should try to keep that stuff separate in the future if possible.

In retrospect, the reformulation is a larger project. I hadn't thought it would be at the time. We could have created a project or milestone for it and created multiple issues related to that. But I think it is too late now, I guess you are nearly finished with the texts, right?

> Do you think it is better if you start (not now, but principally) writing that section instead of me writing things not correct that have to be reworked a lot?

I think that is a good idea, but I don't have much time right now. Since you are reworking all the texts and have a good overview of what terminology needs to be introduced here: Maybe you can collect these as a bullet list already?

**Comment by tutebatti** [comment]
> But I think it is too late now, I guess you are nearly finished with the texts, right?

Nearly, yes. I'm still not happy with consistency regarding different aspects (terminology, formating, structure), but I'm also a perfectionist when it comes to that. I will need to slow down a little on that side.

> Maybe you can collect these as a bullet list already?

Will do. In the html?

**Comment by mfranke93** [comment]
> Nearly, yes. I'm still not happy with consistency regarding different aspects (terminology, formating, structure), but I'm also a perfectionist when it comes to that. I will need to slow down a little on that side.

I just want to repeat that we can also do changes to this stuff *after* the initial publication ;)

> Will do. In the html?

That would be the easiest.

See also [here](https://github.com/UniStuttgart-VISUS/damast/commit/a2e78fa864307319b2d8e3aa28af348a5a5eb2d9#r64589792) for some terminology discussion related to this issue.

**Comment by tutebatti** [comment]
> I just want to repeat that we can also do changes to this stuff _after_ the initial publication ;)

Yes, we can. But no, we should not (too much). ;)
