### ISSUE TITLE
Map glyphs "not encoding data points"

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#78]
In the info text of the _Map_, the following sentences are not clear to me:

> Furthermore, in <em>Clustered mode</em>, the scaling of the map glyphs does <em>not</em> encode number of data points. The glyphs are only scaled such that they occupy the same space regardless of number of circles. The fixed radius is an artifact of the non-overlapping property.

**Comment by mfranke93** [comment]
I gather this is from the "what the map does **not** show" section.

The map glyphs
![image](https://user-images.githubusercontent.com/9373678/151787194-069e1e39-d64c-4388-b3c9-241fbfe21b81.png)
have different perceived size, because some have one circle, some have 2, 3, or 4. In many visualizations, area or radius of markers is used to encode quantitative information. Here, it is not: The size of the marker does **not** say anything about the number of evidences represented by that glyph. The *individual circles* all are the same size.

**Comment by mfranke93** [comment]
> The glyphs are only scaled such that they occupy the same space regardless of number of circles. The fixed radius is an artifact of the non-overlapping property.

This might be too much technical detail for casual visitors. What I mean is that technically, each glyph has the same radius, indicated here:
![image](https://user-images.githubusercontent.com/9373678/151787672-f5273deb-de58-4f9c-bc5c-83d1d0172071.png)

This ensures that they never overlap. Visually, however, if the glyph only has one circle, it seems like it is smaller. In previous versions, glyphs with only one circle had that circle be larger to fill the "blue" circle. However, that looked even more like these places were more important, so we changed it.

**Comment by tutebatti** [comment]
Thanks. This helps a lot. Interestingly, I would not have "read" them as being larger; to me, the idea of multiple circles showing "more" data or anything like that would not have occurred. At any rate, I can rephrase these explanations now.

**Comment by tutebatti** [comment]
> The glyphs are scaled [..., see comments above]

This refers not only to the glyphs as such but also to their clustering, right? Maybe we can delete that altogether? (Originally, I understood that you only think "The fixed radius is an artifact of the non-overlapping property." is too technical.)
