### ISSUE TITLE
Note on "Multiple additonal layers" in info text of "Map"

### ISSUE THREAD

**Issue by tutebatti** [UniStuttgart-VISUS/damast#79]
I am not absolutely sure about the meaning of the following sentence in the info text of the _Map_:

> <em>Note:</em> The density and marker layers for diversity are alternative representations for the same thing and should not be shown together, as they interfere.

**Comment by mfranke93** [comment]
There are two layers for diversity. One shows markers, one for each place in the map, where the coloring shows the religious diversity:
![image](https://user-images.githubusercontent.com/9373678/151786700-709bbc17-ff2b-4aef-a3de-83d479c61221.png)

The other shows the *exact same data,* but as a density estimation. So in the second case, there are not place markers:
![image](https://user-images.githubusercontent.com/9373678/151786862-1286c4d8-176b-4152-85bd-7c5b5f439f99.png)

Since both layers show the same thing, but differently, they should not be shown at the same time. They interfere.

**Comment by mfranke93** [comment]
The design of these two layers is based on extensive and detailed communications with Dorothea. Ask her if you are unsure about why this exists, or what it is used for.

**Comment by tutebatti** [comment]
Thank you for clarification. I think I had trouble with the phrasing. This is what I would suggest:

> _Note:_ The two layers for diversity (one displaying markers, the other displaying a heat map) are _alternative_ representations of the _same_ data. Thus, they should not be both displayed at the same time. Similarly, the two layers using markers (the default one displaying map glyphs and the one displaying markers of diversity) should not be shown together.

Note that the second part of this quotation was not part of my original question.

**Comment by mfranke93** [comment]
I would not call it a "heat map", but rather "density estimation". But other than that, I think the formulation is fine.

**Comment by tutebatti** [comment]
Heatmap is used in the `<dl>` immediately preceding this note. Also "estimation" is not found, rather "approximation" (as a conjugated verb form) is used --- if this is meant to be the same thing at all.

**Comment by mfranke93** [comment]
"Approximation" is fine as well. In that case, the term "heatmap" should be replaced wherever it occurs. There are subtle (technical) differences. For the density layer, it *might* be an acceptable term (but density approximation/estimation is favorable). But the diversity layer does something different entirely, so here it would be wrong to call it heatmap. Can you please update it?

**Comment by tutebatti** [comment]
Will do.
